services:
  # Database Service
  mysql-db:
    image: mysql:8.0
    container_name: quiz-mysql
    restart: always
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_ROOT_PASSWORD: root_password # Change this in production
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service
  backend-api:
    build: ./backend
    container_name: quiz-backend
    restart: on-failure
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/quiz
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
      - JWT_SECRET=UXVpekBBcHBsaWNhdGlvbkBTZWNyZXRAa2V5QDIwMjRASGFyc2hpdEBLdW1hckBTcHJpbmdAQm9vdA==
    ports:
      - "8080:8080"

  # Frontend Service
  frontend-ui:
    build: ./frontend
    container_name: quiz-frontend
    restart: always
    depends_on:
      - backend-api
    ports:
      - "80:80"

volumes:
  db_data:
